services:
  php:
    build: .
    container_name: php-container
    volumes:
      - ./:/var/www/html
      - ./custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
      - ./msmtprc:/etc/msmtprc
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      PHP_INI_SCAN_DIR: /usr/local/etc/php/conf.d  

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - mysql

  mailcatcher:
    image: sj26/mailcatcher
    ports:
      - "1080:1080"  

volumes:
  mysql_data:
